/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_23062025;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        jpb_player.setMinimum(0);
        jpb_player.setMaximum(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpb_player = new javax.swing.JProgressBar();
        btn_play = new javax.swing.JButton();
        btn_pausa = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        btn_avanzar = new javax.swing.JButton();
        btn_retroceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpb_player.setValue(0);

        btn_play.setText("Play");
        btn_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_playMouseClicked(evt);
            }
        });

        btn_pausa.setText("Pausa");

        btn_stop.setText("Detener / Stop");

        btn_avanzar.setText("Avanzar");
        btn_avanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_avanzarMouseClicked(evt);
            }
        });

        btn_retroceder.setText("Retroceder");
        btn_retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_retrocederMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpb_player, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_play)
                                .addGap(113, 113, 113)
                                .addComponent(btn_pausa)
                                .addGap(78, 78, 78)
                                .addComponent(btn_stop))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btn_avanzar)
                        .addGap(64, 64, 64)
                        .addComponent(btn_retroceder)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jpb_player, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_play)
                    .addComponent(btn_pausa)
                    .addComponent(btn_stop))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_avanzar)
                    .addComponent(btn_retroceder))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_avanzarMouseClicked
        int max = jpb_player.getMaximum();
        int val = jpb_player.getValue();
        //random 
        if(val+1 <=max){
            jpb_player.setValue(val+1);
        }else{
            System.out.println("No se puede avanzar");
        }
        
    }//GEN-LAST:event_btn_avanzarMouseClicked

    private void btn_retrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_retrocederMouseClicked
       int min = jpb_player.getMinimum();
        int val = jpb_player.getValue();
        if(val-1 >= min){
            jpb_player.setValue(val-1);
        }else{
            System.out.println("No se puede retroceder");
        }
    }//GEN-LAST:event_btn_retrocederMouseClicked

    private void btn_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_playMouseClicked
        /**
         IMPORTANTE: Los hilos necesitan que se les indique cuando comenzar a trabajar y cuando detenerse. 
         **/
        Thread play = new Thread(() -> {
            int min = jpb_player.getMinimum();
            int max = jpb_player.getMaximum();
            for (int i = min; i < max; i++) {
                try {
                    System.out.println(i);
                    jpb_player.setValue(i);
                    //SIEMPRE RECORDAR QUE EL HILO ASUME QUE LE PASAMOS VALORES EN MILISEGNDO
                    Thread.sleep(200);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
        
        // IMPORTANTE: si no inciamos el hilo este no comenzarà a trabajar, para inciar un hilo sellama al metodo start
        play.start();
        
    }//GEN-LAST:event_btn_playMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avanzar;
    private javax.swing.JButton btn_pausa;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_retroceder;
    private javax.swing.JButton btn_stop;
    private javax.swing.JProgressBar jpb_player;
    // End of variables declaration//GEN-END:variables
}
