/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_02062025;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_pantallaSecundaria = new javax.swing.JDialog();
        lbl_nuevoTexto_dialog = new javax.swing.JLabel();
        txt_nuevoTexto_dilog = new javax.swing.JTextField();
        btn_nuevoTexto_dialog = new javax.swing.JButton();
        lbl_texto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mensaje = new javax.swing.JTextArea();
        jmb_menuPrincipal = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_cargar = new javax.swing.JMenuItem();
        jms_Separador1 = new javax.swing.JPopupMenu.Separator();
        jm_opciones = new javax.swing.JMenu();
        jmi_copiar = new javax.swing.JMenuItem();
        jmi_pegar = new javax.swing.JMenuItem();
        jm_editar = new javax.swing.JMenu();
        jm_test = new javax.swing.JMenu();

        jd_pantallaSecundaria.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nuevoTexto_dialog.setText("Nuevo Texto");
        jd_pantallaSecundaria.getContentPane().add(lbl_nuevoTexto_dialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 67, -1, -1));
        jd_pantallaSecundaria.getContentPane().add(txt_nuevoTexto_dilog, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 102, 444, 122));

        btn_nuevoTexto_dialog.setText("Cambiar Texto");
        btn_nuevoTexto_dialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoTexto_dialogMouseClicked(evt);
            }
        });
        jd_pantallaSecundaria.getContentPane().add(btn_nuevoTexto_dialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 266, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_texto.setText("Texto");

        txt_mensaje.setColumns(20);
        txt_mensaje.setRows(5);
        jScrollPane1.setViewportView(txt_mensaje);

        jm_archivo.setText("Archivo");

        jmi_cargar.setText("Cargar");
        jmi_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cargarActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_cargar);
        jm_archivo.add(jms_Separador1);

        jm_opciones.setText("Opciones");

        jmi_copiar.setText("Copiar");
        jm_opciones.add(jmi_copiar);

        jmi_pegar.setText("Pegar");
        jmi_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pegarActionPerformed(evt);
            }
        });
        jm_opciones.add(jmi_pegar);

        jm_archivo.add(jm_opciones);

        jmb_menuPrincipal.add(jm_archivo);

        jm_editar.setText("Editar");
        jmb_menuPrincipal.add(jm_editar);

        jm_test.setText("Test");
        jmb_menuPrincipal.add(jm_test);

        setJMenuBar(jmb_menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_texto))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbl_texto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_pegarActionPerformed

    private void jmi_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cargarActionPerformed
        txt_mensaje.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at nisl sit amet velit malesuada varius et a dui. Suspendisse quis magna in felis imperdiet euismod. Nam ultricies scelerisque justo. Suspendisse potenti. Phasellus consequat luctus velit sit amet mattis. Aliquam risus ligula, eleifend eget lobortis a, consectetur in sem. Vestibulum semper lacinia pharetra. Vivamus ac lorem eleifend, eleifend purus scelerisque, rhoncus sapien. Fusce malesuada nulla non vulputate ornare.\n" +
"\n" +
"Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sagittis, est non dapibus pellentesque, dui eros porta massa, quis dignissim ligula mi ac risus. Nullam vitae sodales metus. Curabitur sodales accumsan elit ut placerat. Morbi mollis velit sagittis dolor mattis, vel feugiat dui malesuada. Aliquam eu est rutrum, semper ante in, fermentum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in mattis sapien.\n" +
"\n" +
"Nulla non eros vel velit malesuada luctus a non libero. Vestibulum eu faucibus ipsum. Morbi id elementum dolor, sit amet tristique orci. Phasellus ligula ante, porttitor sagittis imperdiet in, sollicitudin ut nisl. Fusce sit amet porta nisi. Mauris accumsan facilisis cursus. Maecenas hendrerit mauris ut dui lacinia pulvinar. Nullam vel orci ex. Fusce in faucibus dui. Morbi non lacinia nibh, id auctor magna.\n" +
"\n" +
"Ut vulputate mi sed cursus mattis. Nulla in auctor metus. Sed elementum ante lorem, id scelerisque justo semper id. Etiam ipsum lectus, tristique ac orci ut, eleifend pellentesque neque. In laoreet fermentum neque, quis fermentum sem. Integer elementum dui sit amet augue semper consectetur. Morbi vehicula metus id placerat finibus. Sed faucibus odio urna, in porta risus bibendum eget. Mauris eu mauris et nunc viverra pharetra vitae vitae eros. Mauris eleifend lorem ut nisl aliquam gravida eu sed metus. Mauris fringilla tincidunt massa in egestas. Sed eros sapien, porta a turpis et, efficitur ultricies sem.");
        
        jd_pantallaSecundaria.setVisible(true);
    }//GEN-LAST:event_jmi_cargarActionPerformed

    private void btn_nuevoTexto_dialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoTexto_dialogMouseClicked
        String texto = txt_nuevoTexto_dilog.getText();
        txt_mensaje.setText(texto);
    }//GEN-LAST:event_btn_nuevoTexto_dialogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nuevoTexto_dialog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_pantallaSecundaria;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenu jm_editar;
    private javax.swing.JMenu jm_opciones;
    private javax.swing.JMenu jm_test;
    private javax.swing.JMenuBar jmb_menuPrincipal;
    private javax.swing.JMenuItem jmi_cargar;
    private javax.swing.JMenuItem jmi_copiar;
    private javax.swing.JMenuItem jmi_pegar;
    private javax.swing.JPopupMenu.Separator jms_Separador1;
    private javax.swing.JLabel lbl_nuevoTexto_dialog;
    private javax.swing.JLabel lbl_texto;
    private javax.swing.JTextArea txt_mensaje;
    private javax.swing.JTextField txt_nuevoTexto_dilog;
    // End of variables declaration//GEN-END:variables
}
