/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_02062025;

import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();   
        //Lista 
        DefaultListModel modelo = new DefaultListModel();
        jl_listaPersonas.setModel(modelo);
        //Tabla
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jt_tabla_usuarios.setModel(modeloTabla);
//        
//        //Agregar columnas.
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Activo");
        
        //Limpiar arbol. 
        DefaultTreeModel modeloArbol = (DefaultTreeModel)jt_usuarios.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)modeloArbol.getRoot();
        raiz.removeAllChildren();
//        modeloArbol.reload();
            //agregar categorias al arbol . 
        DefaultMutableTreeNode nodoDocentes = new DefaultMutableTreeNode("Docentes");  
        DefaultMutableTreeNode nodoAlumno = new DefaultMutableTreeNode("Alumnos");  
        raiz.add(nodoDocentes);
        raiz.add(nodoAlumno);
        
        raiz.setUserObject("USUARIOS");
        modeloArbol.reload();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_pantallaSecundaria = new javax.swing.JDialog();
        lbl_nuevoTexto_dialog = new javax.swing.JLabel();
        txt_nuevoTexto_dilog = new javax.swing.JTextField();
        btn_nuevoTexto_dialog = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbl_texto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mensaje = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lbl_texto_edicion = new javax.swing.JLabel();
        txt_size = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcb_estilo = new javax.swing.JComboBox<>();
        txt_font = new javax.swing.JTextField();
        btn_color = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_font_family = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_color1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcb_tipoUsuario = new javax.swing.JComboBox<>();
        btn_agregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_listaPersonas = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        lbl_nombre_display = new javax.swing.JLabel();
        btn_eliminarLista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_tabla_usuarios = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_columna = new javax.swing.JLabel();
        lbl_fila = new javax.swing.JLabel();
        btn_eliminar_tabla = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_usuarios = new javax.swing.JTree();
        jLabel11 = new javax.swing.JLabel();
        lbl_tipo_seleccion_arbol = new javax.swing.JLabel();
        btn_eliminarArbol = new javax.swing.JButton();
        jmb_menuPrincipal = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_cargar = new javax.swing.JMenuItem();
        jms_Separador1 = new javax.swing.JPopupMenu.Separator();
        jm_opciones = new javax.swing.JMenu();
        jmi_copiar = new javax.swing.JMenuItem();
        jmi_pegar = new javax.swing.JMenuItem();
        jm_editar = new javax.swing.JMenu();
        jm_test = new javax.swing.JMenu();

        jd_pantallaSecundaria.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nuevoTexto_dialog.setText("Nuevo Texto");
        jd_pantallaSecundaria.getContentPane().add(lbl_nuevoTexto_dialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 67, -1, -1));
        jd_pantallaSecundaria.getContentPane().add(txt_nuevoTexto_dilog, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 102, 444, 122));

        btn_nuevoTexto_dialog.setText("Cambiar Texto");
        btn_nuevoTexto_dialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoTexto_dialogMouseClicked(evt);
            }
        });
        jd_pantallaSecundaria.getContentPane().add(btn_nuevoTexto_dialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 266, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_texto.setText("Texto");

        txt_mensaje.setColumns(20);
        txt_mensaje.setRows(5);
        jScrollPane1.setViewportView(txt_mensaje);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_texto)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_texto)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Texto desde dialog", jPanel2);

        lbl_texto_edicion.setText("Hola mundo!");

        jLabel2.setText("Size");

        jLabel3.setText("Estilo");

        jLabel4.setText("Font ");

        jLabel5.setText("Color");

        jcb_estilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plano", "Negrita", "Italica" }));
        jcb_estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_estiloActionPerformed(evt);
            }
        });

        btn_color.setText("seleccionar color");
        btn_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_colorMouseClicked(evt);
            }
        });

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });

        btn_font_family.setText("Actualizar");
        btn_font_family.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_font_familyMouseClicked(evt);
            }
        });

        jLabel6.setText("Color Background");

        btn_color1.setText("seleccionar color");
        btn_color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_color1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lbl_texto_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_font)
                                    .addComponent(btn_color, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_size)
                                    .addComponent(jcb_estilo, 0, 199, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_actualizar)
                            .addComponent(btn_font_family)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_color1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_texto_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_actualizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcb_estilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_font_family))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_color))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_color1))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editor de texto", jPanel1);

        jLabel1.setText("Nombre");

        jLabel7.setText("Tipo de usuario");

        jcb_tipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docente", "Alumno" }));

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        jl_listaPersonas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jl_listaPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_listaPersonasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_listaPersonas);

        jLabel8.setText("Nombre ");

        btn_eliminarLista.setText("Eliminar de a lista");
        btn_eliminarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarListaMouseClicked(evt);
            }
        });

        jt_tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_tabla_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tabla_usuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_tabla_usuarios);

        jLabel9.setText("Columna seleccionada");

        jLabel10.setText("Fila seleccionada");

        btn_eliminar_tabla.setText("Eliminar de la tabla");
        btn_eliminar_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminar_tablaMouseClicked(evt);
            }
        });

        jt_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_usuariosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jt_usuarios);

        jLabel11.setText("Tipo");

        btn_eliminarArbol.setText("Eliminar del arbol");
        btn_eliminarArbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarArbolMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_nombre_display)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(31, 31, 31)
                                        .addComponent(lbl_fila))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_columna))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(153, 153, 153)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(133, 133, 133)
                                                .addComponent(jLabel11)
                                                .addGap(35, 35, 35)
                                                .addComponent(lbl_tipo_seleccion_arbol)))
                                        .addGap(0, 129, Short.MAX_VALUE)))))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre)
                            .addComponent(jcb_tipoUsuario, 0, 219, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_eliminar_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_eliminarArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_eliminarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(167, 167, 167))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jcb_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_eliminarArbol)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btn_eliminarLista)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(btn_agregar))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_eliminar_tabla)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lbl_columna)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbl_fila))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lbl_tipo_seleccion_arbol))
                        .addGap(35, 35, 35)))
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre_display)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Componentes visuales", jPanel3);

        jm_archivo.setText("Archivo");

        jmi_cargar.setText("Cargar");
        jmi_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cargarActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_cargar);
        jm_archivo.add(jms_Separador1);

        jm_opciones.setText("Opciones");

        jmi_copiar.setText("Copiar");
        jm_opciones.add(jmi_copiar);

        jmi_pegar.setText("Pegar");
        jmi_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pegarActionPerformed(evt);
            }
        });
        jm_opciones.add(jmi_pegar);

        jm_archivo.add(jm_opciones);

        jmb_menuPrincipal.add(jm_archivo);

        jm_editar.setText("Editar");
        jmb_menuPrincipal.add(jm_editar);

        jm_test.setText("Test");
        jmb_menuPrincipal.add(jm_test);

        setJMenuBar(jmb_menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_pegarActionPerformed

    private void jmi_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cargarActionPerformed
        txt_mensaje.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at nisl sit amet velit malesuada varius et a dui. Suspendisse quis magna in felis imperdiet euismod. Nam ultricies scelerisque justo. Suspendisse potenti. Phasellus consequat luctus velit sit amet mattis. Aliquam risus ligula, eleifend eget lobortis a, consectetur in sem. Vestibulum semper lacinia pharetra. Vivamus ac lorem eleifend, eleifend purus scelerisque, rhoncus sapien. Fusce malesuada nulla non vulputate ornare.\n" +
"\n" +
"Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sagittis, est non dapibus pellentesque, dui eros porta massa, quis dignissim ligula mi ac risus. Nullam vitae sodales metus. Curabitur sodales accumsan elit ut placerat. Morbi mollis velit sagittis dolor mattis, vel feugiat dui malesuada. Aliquam eu est rutrum, semper ante in, fermentum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in mattis sapien.\n" +
"\n" +
"Nulla non eros vel velit malesuada luctus a non libero. Vestibulum eu faucibus ipsum. Morbi id elementum dolor, sit amet tristique orci. Phasellus ligula ante, porttitor sagittis imperdiet in, sollicitudin ut nisl. Fusce sit amet porta nisi. Mauris accumsan facilisis cursus. Maecenas hendrerit mauris ut dui lacinia pulvinar. Nullam vel orci ex. Fusce in faucibus dui. Morbi non lacinia nibh, id auctor magna.\n" +
"\n" +
"Ut vulputate mi sed cursus mattis. Nulla in auctor metus. Sed elementum ante lorem, id scelerisque justo semper id. Etiam ipsum lectus, tristique ac orci ut, eleifend pellentesque neque. In laoreet fermentum neque, quis fermentum sem. Integer elementum dui sit amet augue semper consectetur. Morbi vehicula metus id placerat finibus. Sed faucibus odio urna, in porta risus bibendum eget. Mauris eu mauris et nunc viverra pharetra vitae vitae eros. Mauris eleifend lorem ut nisl aliquam gravida eu sed metus. Mauris fringilla tincidunt massa in egestas. Sed eros sapien, porta a turpis et, efficitur ultricies sem.");
        
        jd_pantallaSecundaria.setVisible(true);
    }//GEN-LAST:event_jmi_cargarActionPerformed

    private void btn_nuevoTexto_dialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoTexto_dialogMouseClicked
        String texto = txt_nuevoTexto_dilog.getText();
        txt_mensaje.setText(texto);
    }//GEN-LAST:event_btn_nuevoTexto_dialogMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked

        int size = Integer.parseInt(txt_size.getText());
        Font fuenteVieja = lbl_texto_edicion.getFont();
      Font  nuevaFuente = new Font(fuenteVieja.getFontName(),fuenteVieja.getStyle(),size);
      lbl_texto_edicion.setFont(nuevaFuente);


    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_colorMouseClicked
        Color seleccionado = JColorChooser.showDialog(this, "Seleccione un color", Color.WHITE);
        lbl_texto_edicion.setForeground(seleccionado);
//        lbl_texto_edicion.setForeground(JColorChooser.showDialog(this, "Seleccione un color", Color.WHITE));
        
    }//GEN-LAST:event_btn_colorMouseClicked

    private void jcb_estiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_estiloActionPerformed
        int estilo = jcb_estilo.getSelectedIndex();
        Font fuenteVieja = lbl_texto_edicion.getFont();
      Font  nuevaFuente = new Font(fuenteVieja.getFontName(),estilo,fuenteVieja.getSize());
      lbl_texto_edicion.setFont(nuevaFuente);
    }//GEN-LAST:event_jcb_estiloActionPerformed

    private void btn_font_familyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_font_familyMouseClicked
         String nombreFuente = txt_font.getText();
        Font fuenteVieja = lbl_texto_edicion.getFont();
      Font  nuevaFuente = new Font(nombreFuente,fuenteVieja.getStyle(),fuenteVieja.getSize());
      lbl_texto_edicion.setFont(nuevaFuente);
    }//GEN-LAST:event_btn_font_familyMouseClicked

    private void btn_color1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_color1MouseClicked
        Color background = JColorChooser.showDialog(this, "Seleccione un color", Color.red);
        lbl_texto_edicion.setOpaque(true);
        lbl_texto_edicion.setBackground(background);
    }//GEN-LAST:event_btn_color1MouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        int tipo = jcb_tipoUsuario.getSelectedIndex();
        Persona nuevaPersona;
        String tipoUsuario = "";
        if(tipo == 0){ // Docente
           nuevaPersona = new Docente(txt_nombre.getText());
        }else{ //Alumno
            nuevaPersona = new Alumno(txt_nombre.getText());
        }
        //Agregar el objeto nuevaPersona  
        //LISTA
        DefaultListModel modeloLista = (DefaultListModel)jl_listaPersonas.getModel();
        modeloLista.addElement(nuevaPersona);
        //TABLA
        DefaultTableModel modeloTabla = (DefaultTableModel)jt_tabla_usuarios.getModel();
        modeloTabla.addRow(new Object[]{nuevaPersona.getNombre(),jcb_tipoUsuario.getSelectedItem(),false});
        
        //Arbol.
        DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_usuarios.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)modeloArbol.getRoot();
//        if(tipo == 0){ // agregar a la categoria de docentes
//            DefaultMutableTreeNode nodoDocentes= (DefaultMutableTreeNode)raiz.getChildAt(0);
//              DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevaPersona);  
//              nodoDocentes.add(nuevoNodo);
//        }else{ // agregar a la categoria de alumnos 
//            DefaultMutableTreeNode nodoAlumnos= (DefaultMutableTreeNode)raiz.getChildAt(1);
//              DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevaPersona);  
//              nodoAlumnos.add(nuevoNodo);
//        }
      DefaultMutableTreeNode nodo= (DefaultMutableTreeNode)raiz.getChildAt(tipo);
      DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevaPersona);  
      
      /*
      DefaultMutableTreeNode
      hijos: ArraylIST<DefaultMutableTreeNode> 
      UseroBJECT: Object
      
      DefaultMutableTreeNode(Object userObject ){
       this.useroBJECT = userObject
      }
      */
      nodo.add(nuevoNodo);
      modeloArbol.reload();
        
        
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void jl_listaPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_listaPersonasMouseClicked
      int pos = jl_listaPersonas.getSelectedIndex();
      DefaultListModel modeloLista = (DefaultListModel)jl_listaPersonas.getModel();
      Object objetoSeleccionado = modeloLista.getElementAt(pos);
      if(objetoSeleccionado instanceof Docente){
          Docente docenteSeleccionado = (Docente) objetoSeleccionado;
          lbl_nombre_display.setText("DOCENTE: "+docenteSeleccionado.getNombre());
      }else if(objetoSeleccionado instanceof Alumno){
          Alumno alumnoSeleccionado = (Alumno) objetoSeleccionado;
          lbl_nombre_display.setText("ALUMNO: "+alumnoSeleccionado.getNombre());
      }
    }//GEN-LAST:event_jl_listaPersonasMouseClicked

    private void btn_eliminarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarListaMouseClicked
        int pos = jl_listaPersonas.getSelectedIndex();
        DefaultListModel modeloLista = (DefaultListModel)jl_listaPersonas.getModel();
        modeloLista.remove(pos);
        JOptionPane.showMessageDialog(this,"Elemento eliminado");
        
    }//GEN-LAST:event_btn_eliminarListaMouseClicked

    private void jt_tabla_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tabla_usuariosMouseClicked
        int columna = jt_tabla_usuarios.getSelectedColumn();
        int fila = jt_tabla_usuarios.getSelectedRow();
        lbl_fila.setText(fila+"");
        lbl_columna.setText(columna+"");
        DefaultTableModel modelo = (DefaultTableModel) jt_tabla_usuarios.getModel();
        Object objetoSeleccionado = modelo.getValueAt(fila, columna);
        lbl_nombre_display.setText(objetoSeleccionado.toString());
        
        System.out.println("CANTIDAD DE FILAS ");
        System.out.println(modelo.getRowCount());
        System.out.println("CANTIDAD DE COLUMNAS");
        System.out.println(modelo.getColumnCount());
        
//        matriz[i][j] ==modelo.getValueAt(i, j);
    }//GEN-LAST:event_jt_tabla_usuariosMouseClicked

    private void btn_eliminar_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminar_tablaMouseClicked
      int fila = jt_tabla_usuarios.getSelectedRow();
      DefaultTableModel modelo = (DefaultTableModel) jt_tabla_usuarios.getModel();
      modelo.removeRow(fila);
    }//GEN-LAST:event_btn_eliminar_tablaMouseClicked

    private void jt_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_usuariosMouseClicked
//    lbl_tipo_seleccion_arbol
        Object objetoSeleccionado = jt_usuarios.getSelectionPath().getLastPathComponent();
//                                   [RAIZ.....NODO, NODOSELECCIONADO].get(size-1)       
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode)objetoSeleccionado;
        
        if(nodoSeleccionado.isRoot()){
            lbl_tipo_seleccion_arbol.setText("Raiz");
        }else if(nodoSeleccionado.isLeaf()){
            lbl_tipo_seleccion_arbol.setText("Hoja");
        }else{
                lbl_tipo_seleccion_arbol.setText("Nodo");
        }
        
        Object informacion = nodoSeleccionado.getUserObject();
        
        if(informacion instanceof Docente){
          Docente docenteSeleccionado = (Docente) informacion;
          lbl_nombre_display.setText(docenteSeleccionado.getNombre());
        }else if(informacion instanceof Alumno){
            Alumno alumnoSeleccionado = (Alumno) informacion;
            lbl_nombre_display.setText(alumnoSeleccionado.getNombre());
        }
    }//GEN-LAST:event_jt_usuariosMouseClicked

    private void btn_eliminarArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarArbolMouseClicked
         Object objetoSeleccionado = jt_usuarios.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode)objetoSeleccionado;
        DefaultTreeModel modeloArbol =  (DefaultTreeModel) jt_usuarios.getModel();
        if(nodoSeleccionado.isRoot()){
            JOptionPane.showMessageDialog(this, "No se puede eliminar la raiz");
        }else{
            DefaultMutableTreeNode padre = (DefaultMutableTreeNode)nodoSeleccionado.getParent();
            padre.remove(nodoSeleccionado);
            modeloArbol.reload();
             JOptionPane.showMessageDialog(this, "Nodo eliminado");
        }
    }//GEN-LAST:event_btn_eliminarArbolMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_color;
    private javax.swing.JButton btn_color1;
    private javax.swing.JButton btn_eliminarArbol;
    private javax.swing.JButton btn_eliminarLista;
    private javax.swing.JButton btn_eliminar_tabla;
    private javax.swing.JButton btn_font_family;
    private javax.swing.JButton btn_nuevoTexto_dialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcb_estilo;
    private javax.swing.JComboBox<String> jcb_tipoUsuario;
    private javax.swing.JDialog jd_pantallaSecundaria;
    private javax.swing.JList<String> jl_listaPersonas;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenu jm_editar;
    private javax.swing.JMenu jm_opciones;
    private javax.swing.JMenu jm_test;
    private javax.swing.JMenuBar jmb_menuPrincipal;
    private javax.swing.JMenuItem jmi_cargar;
    private javax.swing.JMenuItem jmi_copiar;
    private javax.swing.JMenuItem jmi_pegar;
    private javax.swing.JPopupMenu.Separator jms_Separador1;
    private javax.swing.JTable jt_tabla_usuarios;
    private javax.swing.JTree jt_usuarios;
    private javax.swing.JLabel lbl_columna;
    private javax.swing.JLabel lbl_fila;
    private javax.swing.JLabel lbl_nombre_display;
    private javax.swing.JLabel lbl_nuevoTexto_dialog;
    private javax.swing.JLabel lbl_texto;
    private javax.swing.JLabel lbl_texto_edicion;
    private javax.swing.JLabel lbl_tipo_seleccion_arbol;
    private javax.swing.JTextField txt_font;
    private javax.swing.JTextArea txt_mensaje;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nuevoTexto_dilog;
    private javax.swing.JTextField txt_size;
    // End of variables declaration//GEN-END:variables
}
